export default [
  {
    _id: "A101",
    title: "Propulsion Assignment",
    course: "RS101",
    dueDate: "Oct 5 2023 at 5:00 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 1,
  },
  {
    _id: "A102",
    title: "Combustion Analysis",
    course: "RS101",
    dueDate: "Oct 10 2023 at 5:00 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 2,
  },
  {
    _id: "A103",
    title: "Nozzle Design Project",
    course: "RS101",
    dueDate: "Oct 15 2023 at 5:00 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 3,
  },

  {
    _id: "A201",
    title: "Aerodynamics Quiz",
    course: "RS102",
    dueDate: "Oct 7 2023 at 5:30 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 1,
  },
  {
    _id: "A202",
    title: "Flow Analysis",
    course: "RS102",
    dueDate: "Oct 12 2023 at 5:30 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 2,
  },
  {
    _id: "A203",
    title: "Heating Analysis",
    course: "RS102",
    dueDate: "Oct 17 2023 at 5:30 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 3,
  },

  {
    _id: "A301",
    title: "Structural Design Task",
    course: "RS103",
    dueDate: "Oct 6 2023 at 6:00 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 1,
  },
  {
    _id: "A302",
    title: "Orbital Calculations",
    course: "RS103",
    dueDate: "Oct 11 2023 at 6:00 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 2,
  },
  {
    _id: "A303",
    title: "Systems Engineering Exam",
    course: "RS103",
    dueDate: "Oct 16 2023 at 6:00 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 3,
  },

  {
    _id: "A401",
    title: "Advanced Propulsion Challenges",
    course: "RS101",
    dueDate: "Oct 8 2023 at 6:30 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 1,
  },
  {
    _id: "A402",
    title: "Thrust Vectoring Innovations",
    course: "RS102",
    dueDate: "Oct 13 2023 at 6:30 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 2,
  },
  {
    _id: "A403",
    title: "Rocketry Trends Analysis",
    course: "RS103",
    dueDate: "Oct 18 2023 at 6:30 PM",
    description: "This is a description of the assignment",
    points: 100,
    week: 3,
  },
];
